### ISSUE TITLE
Sentiment analysis

### ISSUE THREAD

**Issue by epetros** [citiususc/Linguakit#10]
Hi, 
There seems to be something wrong with the Sentiment analysis, or I need help understanding its multiple output.
Thanks

**Comment by gamallo** [comment]
Hi, 
This modules gives a polartity (pos, neg, neutral) to each paragraph of the input text. For instance. If your input is:

"Peter is a nice person. 
Paul is not very humble. 
This is my opinion."

The system returns three values, each per paragraph. I've just updated this module in order to make the output clearer (I hope), by adding the text paragraph in the first column. So, the current output would be the following:

```
Peter is a nice person . 	        POSITIVE	0.996803778643914
Paul is not very humble . 	NEGATIVE	0.999608726124624
This is my opinion . 	                NONE	        1
```
 if you have better ideas for the output of this module, please let me know. Thanks.

**Comment by epetros** [comment]
Hi,
I understand it now, thanks for clarifying.
Would suggest maybe adding an overall score as well. Thanks

**Comment by gamallo** [comment]
Yes, your suggestion of adding a total score is just what the demo version does. I updated the module. The last line of the output returns the overall score which is the average of all paragraphs.

**Comment by epetros** [comment]
Great.
